package io.github.hidou7.tolog.classic;

public enum ColumnName {

    EVENT_ID,

    APP_NAME, TIMESTMP, FORMATTED_MESSAGE, LOGGER_NAME, LEVEL_STRING,
    THREAD_NAME, REFERENCE_FLAG, ARG0, ARG1, ARG2, ARG3,
    CALLER_FILENAME, CALLER_CLASS, CALLER_METHOD, CALLER_LINE,

    I, TRACE_LINE;
}
